@echo off
set ENVIRONMENT=production
set GOOGLE_APPLICATION_CREDENTIALS=D:\ws\cloud-github\firebase-production-service-account.json
set MONGO_URL=%CS_MONGO_URL_PRODUCTION%
set JWT_REFRESH_SECRET=%CS_JWT_REFRESH_SECRET_PRODUCTION%
set JWT_TOKEN_SECRET=%CS_JWT_TOKEN_SECRET_PRODUCTION%